import type { TranslationMap } from './types';

export const en: TranslationMap = {
  appName: 'NIGA Patient',
  brandName: 'HelloHomeo',
  tagline: 'Holistic Healing for All',
  byline: 'by Homeocentrum',
  welcomeHeadline: 'Homeopathy.\nWherever You Are.',
  chooseLanguageTitle: 'Choose your language / भाषा निवडा',
  languageNameMarathi: 'मराठी',
  languageNameEnglish: 'English',
  continueInMarathi: 'मराठीत सुरू ठेवा',
  continueInEnglish: 'Continue in English',
  continue: 'Continue',
  teleconsultDisclaimer:
    'HelloHomeo is a teleconsultation service. It is not an emergency service.',
  skip: 'Skip',
  onboardingSlide1Title: 'Find a verified homeopathic doctor',
  onboardingSlide1Body:
    "Search by care need, language, location, fee and availability. Every doctor's registration is verified.",
  onboardingSlide2Title: 'Consult by video, audio or chat',
  onboardingSlide2Body:
    'Join from home on a low-data connection. Audio fallback keeps the consultation going when the network is weak.',
  onboardingSlide3Title: 'Records, prescriptions and medicines in one place',
  onboardingSlide3Body:
    'Your signed prescription, follow-up plan and HomeoMeds delivery status, saved for your whole family.',
  getStarted: 'Get started',
  alreadyHaveAccount: 'I already have an account',
  signInTitle: 'Enter your mobile number',
  signInSubtitle:
    "We'll send a 6-digit OTP to verify it. Your number is never shown to doctors.",
  mobileNumberPlaceholder: 'Mobile number',
  countryCode: '+91',
  sendOtp: 'Send OTP',
  orDivider: 'or',
  bookViaHelpline: 'Book by calling our helpline',
  helplineHint: 'For assisted booking in Marathi — useful on slow networks.',
  signInDisclaimer:
    'HelloHomeo is a teleconsultation service by Homeocentrum. It does not provide emergency care.',
  invalidMobile: 'Enter a valid 10-digit mobile number',
  whatsappConsent:
    'I agree to receive WhatsApp messages from Homeocentrum.',
  whatsappConsentRequired:
    'Please agree to receive WhatsApp messages from Homeocentrum.',
  back: 'Back',
  otpTitle: 'Enter Verification Code',
  otpSubtitle: "We've sent a 6-digit code to your phone number",
  otpDidntReceive: "Didn't receive the code?",
  verify: 'Verify OTP',
  resendOtp: 'Resend OTP',
  otpResendIn: 'Resend code in',
  contactHelpline: 'Contact Helpline',
  getCodeWhatsApp: 'Get code on WhatsApp',
  otpNeedAssistance: 'Need assistance? Reach out to support at',
  otpSupportEmail: 'care@hellohomeo.com',
  profileTitle: 'Complete Profile',
  profileStep: 'Step 1 of 2',
  fullName: 'Full name',
  fullNamePlaceholder: 'Enter your name',
  dateOfBirth: 'Date of birth',
  dateOfBirthPlaceholder: 'dd/mm/yyyy',
  dateOfBirthHint: 'Used to show age-appropriate care',
  gender: 'Gender',
  genderFemale: 'Female',
  genderMale: 'Male',
  genderOther: 'Other',
  preferredLanguage: 'Preferred language',
  preferredLanguagePlaceholder: 'Select language',
  languageHindi: 'हिंदी',
  cityTaluka: 'City / Taluka',
  cityTalukaPlaceholder: 'City / Taluka',
  address: 'Address',
  addressPlaceholder: 'Enter your full address',
  state: 'State',
  statePlaceholder: 'Select state',
  alternateMobile: 'Alternative mobile number',
  email: 'Email address',
  emailPlaceholder: 'example@mail.com',
  referredBy: 'Referred by (optional)',
  referredByPlaceholder: "Doctor or friend's name",
  pincode: 'PIN code',
  pincodePlaceholder: 'PIN code',
  accessibilityNeeds: 'Accessibility needs (optional)',
  preferAudioConsult: 'I prefer audio consultation',
  needLargeText: 'I need larger text',
  needCallAssistance: 'I need assistance to join calls',
  profilePrivacyNote:
    'Only your name, age and the details you share during consultation are visible to your doctor. Your mobile number stays masked.',
  skipForNow: 'Skip for now',
  consentTitle: 'Your privacy and consent',
  consentStep: 'Step 2 of 2',
  consentIntro:
    'You control what you share. Each permission below is separate — you can turn any of them off later in Account > Consent Centre.',
  privacyNoticeVersion: 'Privacy Notice v1.2 · effective 28 Aug 2026',
  readFullNotice: 'Read full notice',
  privacyNoticeTitle: 'Privacy Notice',
  consentRequired: 'Required',
  consentTeleconsultTitle: 'Teleconsultation',
  consentTeleconsultBody:
    'Allow a verified doctor to consult you online and record clinical notes.',
  consentRecordsTitle: 'Share my health records with the doctor I book',
  consentRecordsBody:
    'Lets your doctor see your past prescriptions and uploaded documents.',
  consentPharmacyTitle: 'Medicine delivery (HomeoMeds)',
  consentPharmacyBody:
    'Share only the prescription details a licensed pharmacy needs to prepare your order.',
  consentUpdatesTitle: 'Updates and health tips',
  consentUpdatesBody:
    'Offers, articles and reminders on WhatsApp, SMS or email.',
  consentRecordingNote:
    'Consultation recording is asked separately, only at the time of the consultation.',
  agreeAndContinue: 'Agree and continue',
  manageLater: 'Manage later',
  close: 'Close',
  done: 'Done',
  cancel: 'Cancel',
  familyMembersTitle: 'Family members',
  familyHelp: 'Help',
  familyMembersYouManage: 'Members you manage',
  familyAdultConfirmNote:
    'For members aged 18 and above, they must confirm on their own mobile number before you can book or view records.',
  familyAddMember: 'Add family member',
  familyYouBadge: 'You',
  familyGuardianBadge: 'Guardian',
  familyPendingBadge: 'Authorization pending',
  familyAuthorizedBadge: 'Authorized',
  yearsShort: 'yrs',
  relationship: 'Relationship',
  relationshipPlaceholder: 'Select relationship',
  relationshipSpouse: 'Spouse',
  relationshipChild: 'Child',
  relationshipParent: 'Parent',
  relationshipSibling: 'Sibling',
  relationshipOther: 'Other',
  familyMobileHint: 'Required for members 18 and above',
  familyManageConsent:
    "I confirm I am authorized to manage this person's health records",
  familySendAuthRequest: 'Send authorization request',
  familyRemoveMember: 'Remove member',
  familyMoreOptions: 'More options',
  addFamilyMemberTitle: 'Add family member',
  homeTitle: 'Welcome',
  homeSubtitle: 'NIGA Homeocentrum',
  homeHello: 'Namaskar',
  homeForWhom: 'For whom',
  homeForPrefix: 'For',
  homeForMyself: 'Myself',
  homeSearchPlaceholder: 'Search doctors or care needs',
  homeNextConsultation: 'Next consultation',
  homeDoctorName: 'Dr. Anjali Deshmukh',
  homeDoctorQualification: 'B.H.M.S. - Homeopathy Specialist',
  homeVerified: 'Verified',
  homeConsultWhen: 'Today, 6:30 PM · Video',
  homeConsultDate: 'Today, 6:30 PM',
  homeConsultMode: 'Video',
  homeStartsIn: 'Starts in 42 min',
  homeJoinConsultation: 'Join consultation',
  homeFollowUpDue: 'Follow-up due for Aarav',
  homeFillSymptomDiary: 'Fill symptom diary',
  homeOrderNumber: 'Order #HM-4821',
  homeOrderOutForDelivery: 'Out for delivery',
  homeHomeoMedsOrder: 'HomeoMeds order',
  homeTrack: 'Track',
  homeQuickActions: 'Quick Actions',
  homeBookConsultation: 'Book a consultation',
  homeInstantAdvice: 'Consult now',
  homeInstantBadge: 'Instant',
  homeMyPrescriptions: 'My prescriptions',
  homeOrderMedicines: 'Order medicines',
  homeCareCategories: 'Care Categories',
  homeViewAll: 'View all',
  homeCatSkin: 'Skin',
  homeCatAllergy: 'Allergy & Respiratory',
  homeCatDigestion: 'Digestive',
  homeCatWomensHealth: "Women's health",
  homeCatChildCare: 'Child care',
  homeHealthTips: 'Health tips',
  homeTipCategory: 'Lifestyle and chronic conditions',
  homeTipTitle: 'How to boost immunity with homeopathy',
  homeTipExcerpt:
    'Simple, natural ways to stay well in the monsoon. The right diet and considered use of homeopathic medicines...',
  homeTipReviewedBy: 'Reviewed by Dr. N. Jamdar',
  tipMinRead: '{count} min read',
  tipSave: 'Save article',
  tipSaved: 'Saved',
  tipShare: 'Share article',
  tipTextSize: 'Text size',
  tipReviewedBy: 'Reviewed by {name}',
  tipReadReviewNotes: 'Read review notes',
  tipHideReviewNotes: 'Hide review notes',
  tipDailyCare: 'Daily Care Tips',
  tipDisclaimerTitle: 'What this article is not:',
  tipDisclaimerBody:
    'This is general education. It is not a diagnosis, a prescription, or a substitute for a consultation with a registered homoeopathic practitioner.',
  tipTalkToDoctor: 'Talk to a doctor about this',
  tipTalkToDoctorBody:
    "Get personalized advice for your child's specific symptoms.",
  tipFindSkinDoctor: 'Find a skin-care doctor',
  tipFindAllergyDoctor: 'Find an allergy doctor',
  tipFindLifestyleDoctor: 'Find a doctor',
  tipRelatedReading: 'Related Reading',
  tipHelpful: 'Was this article helpful?',
  tipReport: 'Report inaccurate information',
  tipCatRespiratory: 'Respiratory',
  tipCatWellness: 'Wellness',
  tipEczemaTitle: 'Eczema in children — what to expect from homeopathic care',
  tipEczemaExcerpt:
    'Gentle, whole-child care for itchy, inflamed skin — and what a homoeopathic consultation usually looks like.',
  tipEczemaAuthorCreds: 'B.H.M.S., M.D. • Reg No: HGM-2453',
  tipEczemaReviewer: 'Dr. Nikhil Bondar',
  tipEczemaPublished: 'Published & Reviewed 12 Aug 2024',
  tipEczemaReviewNotes:
    'Reviewed for clinical accuracy and plain-language safety. Homeocentrum notes that individual treatment is always based on the child’s full case, not this article alone.',
  tipEczemaH1: 'Understanding childhood eczema',
  tipEczemaP1:
    'Eczema (atopic dermatitis) is common in children. The skin becomes dry, itchy, and easily inflamed. Flares often come and go. A homoeopathic consultation looks at the whole child — sleep, digestion, mood, family history, and what makes the itch better or worse — not only the patches on the skin.',
  tipEczemaQuote:
    'Homeopathy looks at the child as a whole, not just the skin condition. We aim to understand the underlying susceptibility.',
  tipEczemaCheck1: 'Environmental factors — heat, dust, pollen, and dry air can trigger flares.',
  tipEczemaCheck2: 'Irritants — harsh soaps, wool, and frequent sanitiser dry the skin barrier.',
  tipEczemaCheck3: 'Stress — poor sleep, exams, or family upset can worsen itching.',
  tipEczemaH2: 'The Homeopathic approach',
  tipEczemaP2:
    'The aim is to reduce susceptibility over time, not only to suppress the itch. A registered practitioner takes a detailed case, selects a medicine for that child, and reviews how sleep, mood, and skin respond. Daily skin care still matters: short lukewarm baths, gentle drying, and a bland moisturiser support the barrier while treatment is underway.',
  tipEczemaCare1: 'Keep baths short and lukewarm — hot water strips oils from the skin.',
  tipEczemaCare2: 'Pat the skin dry gently. Do not rub.',
  tipEczemaCare3: 'Moisturise while the skin is still slightly damp.',
  tipEczemaCare4: 'Choose cotton clothing and skip harsh soaps or fragrance.',
  tipAllergyTitle: 'Understanding childhood allergies & triggers',
  tipAllergyExcerpt:
    'How homoeopathic care looks at repeated colds, sneezing, and seasonal flares in children.',
  tipAllergyPublished: 'Published & Reviewed 4 Aug 2024',
  tipAllergyReviewNotes:
    'Reviewed for educational accuracy. Allergies can overlap with infection; a doctor should assess breathing difficulty or sudden swelling as urgent.',
  tipAllergyH1: 'Repeated colds are not always “just a virus”',
  tipAllergyP1:
    'Many children sneeze, wheeze, or get a blocked nose in the same season every year. Dust, pollen, and change of weather are common triggers. A homoeopathic case also notes how the child sleeps, eats, and recovers between episodes.',
  tipAllergyQuote:
    'We treat the child who gets the allergy, not only the sneeze of the day.',
  tipAllergyH2: 'What to expect in a consultation',
  tipAllergyP2:
    'Bring a simple diary of flares — time of day, food, dust, and sleep. The practitioner may still advise you to continue any inhaler or emergency plan already prescribed by another doctor.',
  tipAllergyCare1: 'Rinse dust from bedding and soft toys regularly.',
  tipAllergyCare2: 'Keep the child’s room aired and smoke-free.',
  tipAllergyCare3: 'Note foods or weather that reliably start a flare.',
  tipImmunityPublished: 'Published & Reviewed 28 Jul 2024',
  tipImmunityReviewer: 'Dr. N. Jamdar',
  tipImmunityReviewNotes:
    'Lifestyle guidance only. Acute high fever, breathing distress, or a very unwell child needs prompt medical review.',
  tipImmunityH1: 'Small daily habits that support recovery',
  tipImmunityP1:
    'Sleep, warm cooked food, and unhurried play do more for a child’s resilience than a cupboard of supplements. Homoeopathic medicines are selected for the person, and are not a replacement for vaccines or emergency care.',
  tipImmunityQuote:
    'Immunity is the child’s pattern of response — we support that pattern, we do not force it.',
  tipImmunityP2:
    'In monsoon, keep feet dry, meals regular, and rest when a cold starts. A practitioner can advise if a medicine is appropriate after taking the case.',
  tipImmunityCare1: 'Keep a regular sleep time, even on weekends.',
  tipImmunityCare2: 'Offer warm, simple meals rather than frequent packaged snacks.',
  tipImmunityCare3: 'Let mild colds run with rest and fluids unless a doctor advises otherwise.',
  homeTabHome: 'Home',
  homeTabDoctors: 'Doctors',
  homeTabRecords: 'Records',
  homeTabMedicines: 'Medicines',
  homeTabAccount: 'Account',
  homeNotifications: 'Notifications',
  homeComingSoon: 'Coming soon',
  searchDoctorsTitle: 'Search Doctors',
  searchPlaceholder: 'Doctor name, care need or location',
  searchVoice: 'Voice search',
  searchListening: 'Listening…',
  searchVoicePermissionDenied:
    'Allow microphone and speech recognition to search by voice.',
  searchVoiceUnavailable: 'Voice search is not available on this device.',
  searchVoiceLanguageUnsupported:
    'Voice search is not available for this language.',
  searchRecentHeading: 'RECENT SEARCHES',
  searchRecentSkin: 'Skin complaints',
  searchRecentDoctor: 'Dr. Deshmukh',
  searchRecentChild: 'Child care in Solapur',
  searchRemoveRecent: 'Remove',
  searchTalkNow: 'Talk to an available doctor now',
  searchTypicalWait: 'Typical wait 4–8 minutes',
  searchSeeAvailability: 'See availability',
  searchBrowseCareNeed: 'Browse by care need',
  searchCareSkin: 'Skin complaints',
  searchCareSkinHint: 'Eczema, acne, hair',
  searchCareAllergy: 'Allergy & respiratory',
  searchCareAllergyHint: 'Cold, asthma, sinus',
  searchCareDigestive: 'Digestive care',
  searchCareDigestiveHint: 'Acidity, IBS, appetite',
  searchCareWomen: "Women's health",
  searchCareWomenHint: 'Cycle, menopause, PCOS',
  searchCareChild: 'Child care',
  searchCareChildHint: 'Growth, immunity, colic',
  searchCarePain: 'Pain & joints',
  searchCarePainHint: 'Back, knee, arthritis',
  searchCareLifestyle: 'Lifestyle & chronic care',
  searchCareLifestyleHint: 'Sleep, stress, thyroid',
  searchCareDisclaimer:
    'Care needs help you find the right doctor. They are not a diagnosis.',
  searchNearYou: 'Near you',
  searchLocation: 'Location',
  searchDoctorOpen: 'View doctor',
  searchCitySolapur: 'Solapur',
  searchCityPune: 'Pune',
  searchCityMumbai: 'Mumbai',
  searchDoctorJoshiName: 'Dr. A. Joshi',
  searchDoctorJoshiMeta: 'BHMS • 15 yrs exp',
  searchDoctorJoshiPlace: 'Solapur North • 2.5 km',
  searchDoctorPatilName: 'Dr. S. Patil',
  searchDoctorPatilMeta: 'BHMS • 12 yrs exp',
  searchDoctorPatilPlace: 'Solapur East • 4.1 km',
  searchResultsTitle: 'Search Results',
  searchFilters: 'Filters',
  searchSortRelevance: 'Sort: Relevance',
  searchFilterVideo: 'Video',
  searchFilterMarathi: 'मराठी',
  searchFilterAvailableToday: 'Available today',
  searchFilterUnder500: 'Under ₹500',
  searchResultsCount: '18 verified doctors',
  searchResultsWhyOrder: 'Why this order?',
  searchResultsWhyOrderBody:
    'Results are ordered by relevance, availability, and verification. Paid placements are marked Sponsored and do not change ranking or referrals.',
  searchLangMarathi: 'मराठी',
  searchLangEnglish: 'English',
  searchLangHindi: 'Hindi',
  searchModeVideo: 'Video',
  searchModeClinic: 'Clinic',
  searchSponsored: 'Sponsored',
  searchPaidPlacement:
    'Paid placement. Ranking and referrals are not affected.',
  searchCertifiedBanner:
    'Homeocentrum Certified Focus Practitioner — Skin Care',
  searchBook: 'Book',
  searchConsultation: 'consultation',
  searchResultAnjaliName: 'Dr. Anjali Deshmukh',
  searchResultAnjaliCredentials:
    'B.H.M.S., M.D. (Homoeopathy) — Practice of Medicine',
  searchResultAnjaliReg: 'Reg. MH-HOM-24581',
  searchResultAnjaliExperience: '12 yrs experience · Solapur',
  searchResultAnjaliReviews: '(212 reviews)',
  searchResultAnjaliFee: '₹600',
  searchResultAnjaliWhen: 'Today 6:30 PM',
  searchResultRajeshName: 'Dr. Rajesh Patil',
  searchResultRajeshCredentials: 'B.H.M.S.',
  searchResultRajeshExperience: '8 yrs experience · Pune',
  searchResultRajeshReviews: '(85 reviews)',
  searchResultRajeshFee: '₹400',
  searchResultRajeshWhen: 'Tomorrow 10:00 AM',
  searchResultSunitaName: 'Dr. Sunita Sharma',
  searchResultSunitaCredentials: 'M.D. Dermatology',
  searchResultSunitaExperience: '15 yrs experience · Mumbai',
  searchResultSunitaReviews: '(540 reviews)',
  searchResultSunitaFee: '₹800',
  searchResultSunitaWhen: 'Available in 30 mins',
  searchResultsEmptyTitle: 'No verified doctors match these filters',
  searchResultsEmptyBody:
    "We couldn't find any practitioners available right now with your specific requirements. Try adjusting your search or clearing some filters.",
  searchResultsClearFilters: 'Clear all filters',
  searchResultsBookAssistance: 'Book with assistance',
  searchResultsHelplinePrefix: 'Need urgent care? Call our helpline: ',
  searchResultsHelplineNumber: '104',
  searchAllFilters: 'All Filters',
  searchFilterSpecialty: 'Specialty: Dermatology',
  searchFilterAvailabilityTodayLabel: 'Availability: Today',
  searchFilterLanguageMarathi: 'Language: Marathi',
  searchSortDistance: 'Sort: Distance',
  filterResetAll: 'Reset all',
  filterCareNeed: 'Care need',
  filterConsultMode: 'Consultation method',
  filterModeAudio: 'Audio',
  filterModeChat: 'Chat',
  filterModeClinicVisit: 'Clinic visit',
  filterAvailability: 'Availability',
  filterAvailableNow: 'Available now',
  filterToday: 'Today',
  filterTomorrow: 'Tomorrow',
  filterSelectDate: 'Select date',
  filterFeeRange: 'Fee range',
  filterFeeUnder500: 'Under ₹500',
  filterFee500to1000: '₹500–₹1000',
  filterFeeMin: '₹200',
  filterFeeMax: '₹2,000',
  filterDoctorSection: 'Doctor',
  filterQualifications: 'Qualification & certificates',
  filterRecognizedQual: 'Recognised qualification',
  filterFocusCert: 'Homeocentrum Focus certificate',
  filterLocation: 'Location',
  filterLocationPlaceholder: 'Search city or area',
  filterCurrentLocation: 'My current location',
  filterResultsDisclaimer:
    'Your search results are ranked by doctor availability and your search criteria.',
  filterShowDoctors: 'Show {count} doctors',
  filterClear: 'Clear',
  profileShare: 'Share',
  profileSave: 'Save',
  profileSaved: 'Saved',
  profileTabAbout: 'About',
  profileTabCredentials: 'Credentials',
  profileTabReviews: 'Reviews',
  profileTabAvailability: 'Availability',
  profileVerifiedBy: 'Verified by Homeocentrum',
  profileQualVerified: 'Qualification verified',
  profileLicensed: 'Currently licensed to practise',
  profileViewDetails: 'View details',
  profileReadMore: 'Read more',
  profileReadLess: 'Read less',
  profileCareFocus: 'Care Focus',
  profileCareFocusNote:
    'Care needs this doctor commonly treats. Not a diagnosis or a guarantee of outcome.',
  profileConsultations: 'Consultations',
  profileVideoConsult: 'Video consultation',
  profileAudioConsult: 'Audio consultation',
  profileFollowUpChat: 'Follow-up chat',
  profileFollowUpChatHint:
    "Window set by this doctor's current service plan and shown before you pay.",
  profileIncluded: 'Included',
  profileClinicVisit: 'Clinic visit',
  profileConsultationFee: 'Consultation fee',
  profileBookConsultation: 'Book consultation',
  profileDetailsTitle: 'Verification details',
  profileLanguagesSpoken: 'Languages spoken',
  profileNoSlots: 'No more slots to show right now.',
  credAndVerification: 'Credentials & Verification',
  credRecognisedTitle: 'Recognised medical qualifications',
  credRecognisedNote:
    'Qualifications recognised under the National Commission for Homoeopathy.',
  credVerified: 'Verified',
  credLicensedBadge: 'Currently licensed',
  credStatusActive: 'Status: Active',
  credFocusTitle: 'Homeocentrum focus credentials',
  credFocusWarning:
    'These are Homeocentrum professional-development credentials. They are NOT a recognised medical speciality and do not make a doctor a specialist.',
  credActive: 'Active',
  credVerifyCertificate: 'Verify certificate',
  credCareLinkTitle: 'CareLink network role',
  credCareLinkNote:
    'An internal referral and responsibility level in the Homeocentrum network. It is not a medical qualification or a public speciality title.',
  credSomethingWrong: 'Something look wrong?',
  credReportsGoTo: 'Reports go to Homeocentrum Clinical Governance.',
  credReportError: 'Report a profile error',
  credReportProfileLink: 'Report Profile | प्रोफाईल तक्रार करा',
  credPrivacyLink: 'Privacy Policy | गोपनीयता धोरण',
  credNetworkCopyright: 'Verified Homeopathy Network © 2024',
  credAnjaliMdTitle: 'M.D. (Homoeopathy) — Practice of Medicine',
  credAnjaliMdDetail: 'Government Homoeopathic Medical College, Pune · 2016',
  credAnjaliMdBadge: 'Verified on 12 Aug 2026',
  credAnjaliBhmsTitle: 'B.H.M.S.',
  credAnjaliBhmsDetail: 'Maharashtra University of Health Sciences · 2012',
  credAnjaliRegTitle: 'Registration No. MH-HOM-24581',
  credAnjaliCouncil: 'Council: Maharashtra Council of Homoeopathy',
  credAnjaliValid: 'Valid till: 31 Mar 2028',
  credAnjaliFocusTitle: 'Homeocentrum Certified Focus Practitioner — Skin Care',
  credAnjaliFocusId: 'Certificate ID HC-FP-SKN-0912 · Issued 04 Feb 2026',
  credAnjaliFocusValid: 'Valid till 04 Feb 2029',
  credAnjaliCareLinkTitle: 'District Consultant · CareLink',
  credAnjaliCareLinkQuote:
    '“Reviews cases referred by taluka and network doctors.”',
  credRajeshBhmsTitle: 'B.H.M.S.',
  credRajeshBhmsDetail: 'Maharashtra University of Health Sciences · 2016',
  credRajeshRegTitle: 'Registration No. MH-HOM-18820',
  credRajeshValid: 'Valid till: 31 Mar 2027',
  credRajeshFocusTitle:
    'Homeocentrum Certified Focus Practitioner — Pain & Lifestyle',
  credRajeshFocusId: 'Certificate ID HC-FP-PAIN-0440 · Issued 10 Jan 2026',
  credRajeshFocusValid: 'Valid till 10 Jan 2029',
  credRajeshCareLinkTitle: 'Network Doctor · CareLink',
  credRajeshCareLinkQuote:
    '“Provides first-line homeopathic care and refers complex cases.”',
  credSunitaMdTitle: 'M.D. (Homoeopathy) — Practice of Medicine',
  credSunitaMdDetail: 'Government Homoeopathic Medical College, Mumbai · 2011',
  credSunitaMdBadge: 'Verified on 18 Aug 2026',
  credSunitaBhmsTitle: 'B.H.M.S.',
  credSunitaBhmsDetail: 'Maharashtra University of Health Sciences · 2008',
  credSunitaRegTitle: 'Registration No. MH-HOM-10214',
  credSunitaValid: 'Valid till: 31 Mar 2028',
  credSunitaFocusTitle: 'Homeocentrum Certified Focus Practitioner — Skin Care',
  credSunitaFocusId: 'Certificate ID HC-FP-SKN-0718 · Issued 22 Mar 2026',
  credSunitaFocusValid: 'Valid till 22 Mar 2029',
  credSunitaCareLinkTitle: 'District Consultant · CareLink',
  credSunitaCareLinkQuote:
    '“Reviews skin-care referrals from network doctors.”',
  profileAnjaliExp: '12 yrs exp',
  profileAnjaliConsults: '1,840 consults',
  profileAnjaliAbout:
    'Dr. Anjali Deshmukh is a dedicated Homoeopathic physician with over a decade of experience in treating a wide range of acute and chronic conditions. She believes in a holistic approach to patient care, focusing on understanding the root cause of illness rather than just suppressing symptoms. Her gentle and empathetic manner ensures that every patient feels heard and cared for.',
  profileAnjaliRegVerified: 'Reg. MH-HOM-24581 verified',
  profileAnjaliLastVerified: 'Last verified 12 Aug 2026',
  profileAnjaliNext: 'Next available Wed, 26 Aug, 6:30 PM',
  profileAnjaliClinicFee: '₹500',
  profileRajeshExp: '8 yrs exp',
  profileRajeshConsults: '640 consults',
  profileRajeshAbout:
    'Dr. Rajesh Patil focuses on everyday homeopathic care for families in Pune. He keeps consultations clear and practical, and follows up so treatment stays easy to continue at home.',
  profileRajeshRegVerified: 'Registration verified',
  profileRajeshLastVerified: 'Last verified 4 Aug 2026',
  profileRajeshNext: 'Next available Tomorrow, 10:00 AM',
  profileSunitaExp: '15 yrs exp',
  profileSunitaConsults: '3,120 consults',
  profileSunitaAbout:
    'Dr. Sunita Sharma is a dermatology-focused homeopathic practitioner in Mumbai. She helps patients with long-standing skin concerns using a calm, stepwise plan.',
  profileSunitaRegVerified: 'Registration verified',
  profileSunitaLastVerified: 'Last verified 18 Aug 2026',
  profileSunitaNext: 'Next available in 30 mins',
  profileSunitaClinicFee: '₹700',
  profileReview1Name: 'Priya K.',
  profileReview1Body:
    'Listened carefully and explained the plan in simple words. My skin has been much calmer after the follow-up.',
  profileReview1Date: '2 weeks ago',
  profileReview2Name: 'Sanjay M.',
  profileReview2Body:
    'Punctual video consult. Clear guidance on diet and medicines. Would book again.',
  profileReview2Date: '1 month ago',
  doctorsTabSubtitle: 'Find verified homeopathy doctors near you',
  languageLabel: 'Language',
  english: 'English',
  marathi: 'Marathi',
  loading: 'Loading',
  splashLoadingEn: 'LOADING...',
  splashLoadingMr: 'लोड होत आहे...',
  networkError: 'Unable to connect. Check your internet connection.',
  genericError: 'Something went wrong. Please try again.',
  emptyState: 'Nothing to show yet.',
  retry: 'Try again',
  accountEditProfile: 'Edit profile',
  accountSectionMyCare: 'MY CARE',
  accountFamilyMembers: 'Family members',
  accountFamilyMembersBadge: '4 members',
  accountAppointments: 'My appointments',
  accountPrescriptions: 'My prescriptions',
  accountHealthRecords: 'Health records',
  accountHealthInsights: 'Health insights',
  accountPainPoints: 'Pain points',
  accountReminders: 'Reminders',
  accountRemindersBadge: '6 active',
  accountCareLink: 'CareLink referrals',
  accountCareLinkBadge: '1 active',
  accountSectionWellness: 'WELLNESS',
  accountNonClinical: 'Non-clinical',
  accountAstroWellness: 'Astro-wellness',
  accountAstroHelper: 'Optional traditional guidance. Not medical advice.',
  accountBirthDetails: 'Birth details',
  accountSectionPreferences: 'PREFERENCES',
  accountAccessibility: 'Accessibility',
  accountAccessibilityValue: 'Larger text on',
  accountLowDataMode: 'Low-data mode',
  accountLowDataHelper:
    'Loads text first and skips images. Recommended on slow networks.',
  accountSectionPayments: 'PAYMENTS',
  accountPaymentMethods: 'Payment methods',
  accountPaymentMethodsBadge: '2 saved',
  accountPaymentsReceipts: 'Payments & receipts',
  accountMembership: 'Membership',
  accountComingSoon: 'Coming soon',
  accountSectionPrivacy: 'PRIVACY & SECURITY',
  accountConsentCentre: 'Consent Centre',
  accountConsentBadge: '5 permissions',
  accountDataRequests: 'My data requests',
  accountLoginActivity: 'Login activity',
  accountLoginActivityBadge: '3 devices',
  accountDownloadData: 'Download my data',
  accountSectionHelp: 'HELP',
  accountHelpCentre: 'Help centre',
  accountSupportTickets: 'My support tickets',
  accountSupportTicketsBadge: '1 open',
  accountAbout: 'About HelloHomeo',
  accountTerms: 'Terms of use',
  accountPrivacyNotice: 'Privacy notice',
  accountPrivacyNoticeVersion: 'v1.2',
  accountLogOut: 'Log out',
  accountDeleteAccount: 'Delete my account',
  accountDeleteAccountNote:
    'Some records must be kept by law even after deletion — we’ll explain what and why.',
  bookTitle: 'Book Appointment',
  bookMore: 'More',
  bookConsultingFor: 'Consulting for:',
  bookMode: 'Consultation Mode',
  bookVideo: 'Video',
  bookAudio: 'Audio',
  bookClinic: 'Clinic',
  bookSelectDate: 'Select Date',
  bookSelectMonth: 'Select month',
  bookAugust: 'August',
  bookToday: 'Today',
  bookWed: 'Wed',
  bookThu: 'Thu',
  bookFri: 'Fri',
  bookSat: 'Sat',
  bookSun: 'Sun',
  bookMon: 'Mon',
  bookTue: 'Tue',
  bookSlots: 'Available Slots',
  bookMorning: 'Morning',
  bookAfternoon: 'Afternoon',
  bookEvening: 'Evening',
  bookSlotsCount: '{count} slots',
  bookTimezone: 'All times shown in IST (Indian Standard Time)',
  bookSummary: 'Selection Summary',
  bookWhoFor: 'Who is this for?',
  bookMyself: 'Myself',
  bookAddMember: 'Add Family Member',
  bookAaravMeta: '6 yrs • Son',
  bookMeeraMeta: '31 yrs • Spouse',
  bookMonthJan: 'January',
  bookMonthFeb: 'February',
  bookMonthMar: 'March',
  bookMonthApr: 'April',
  bookMonthMay: 'May',
  bookMonthJun: 'June',
  bookMonthJul: 'July',
  bookMonthAug: 'August',
  bookMonthSep: 'September',
  bookMonthOct: 'October',
  bookMonthNov: 'November',
  bookMonthDec: 'December',
  bookWaitlistTitle: 'All slots taken on {date}',
  bookWaitlistBody:
    'We’ll offer you a slot if one frees up. The offer expires in 30 minutes.',
  bookJoinWaitlist: 'Join waitlist',
  bookWaitlistSummary: 'Waitlist · {date}',
  bookAnjaliShortCreds: 'B.H.M.S., M.D. (Hom.)',
  bookRajeshShortCreds: 'B.H.M.S.',
  bookSunitaShortCreds: 'M.D. (Homoeopathy)',
  bookSlot0900: '09:00 AM',
  bookSlot0930: '09:30 AM',
  bookSlot1000: '10:00 AM',
  bookSlot1030: '10:30 AM',
  bookSlot1100: '11:00 AM',
  bookSlot1130: '11:30 AM',
  bookSlot1300: '01:00 PM',
  bookSlot1330: '01:30 PM',
  bookSlot1400: '2:00 PM',
  bookSlot1430: '02:30 PM',
  bookSlot1530: '3:30 PM',
  bookSlot1700: '5:00 PM',
  bookSlot1800: '6:00 PM',
  bookSlot1830: '6:30 PM',
  bookSlot1900: '7:00 PM',
  bookSlot1930: '7:30 PM',
  bookSummaryWed26: 'Wed, 26 Aug 2026',
  bookSummaryThu27: 'Thu, 27 Aug 2026',
  bookSummaryFri28: 'Fri, 28 Aug 2026',
  bookSummarySat29: 'Sat, 29 Aug 2026',
  bookSummarySun30: 'Sun, 30 Aug 2026',
  bookSummaryMon31: 'Mon, 31 Aug 2026',
  bookSummaryTue01: 'Tue, 1 Sep 2026',
  reviewTitle: 'Review & Consent',
  reviewWhen: 'When',
  reviewMode: 'Mode',
  reviewPatient: 'Patient',
  reviewChange: 'Change',
  reviewVideoConsult: 'Video consultation',
  reviewAudioConsult: 'Audio consultation',
  reviewClinicVisit: 'Clinic visit',
  reviewReason: 'Reason for Visit',
  reviewReasonPlaceholder: 'Briefly describe the main concern (optional)',
  reviewAttach: 'Attach a report or photo',
  reviewAttachHint: 'JPG, PNG or PDF up to 10 MB.',
  reviewAttachFile: 'skin-report.pdf',
  reviewRemoveAttach: 'Remove',
  reviewPayment: 'Payment Summary',
  reviewDoctorFee: "Doctor's professional fee",
  reviewPlatformFee: 'HelloHomeo platform fee',
  reviewTaxes: 'Taxes',
  reviewTotalPayable: 'Total payable',
  reviewPriceLocked:
    'This price is locked for this booking. No further convenience or platform charge is added later.',
  reviewConsents: 'Consents',
  reviewDataConsent:
    'I consent to the processing of my personal data for this online consultation',
  reviewDataConsentBody:
    'Your data will be used solely for clinical history taking and digital prescription issuance by the selected healthcare professional.',
  reviewShareRecords: 'Share my past records with this doctor',
  reviewShareRecordsBody:
    'Previous prescriptions, notes and uploaded documents for this patient only.',
  reviewReminders: 'Allow this doctor to add follow-up reminders.',
  reviewRecordingNote:
    'Recording is never automatic. If the doctor wishes to record, you will be asked separately at the start of the consultation.',
  reviewPolicy: 'Reschedule & cancellation policy',
  reviewPolicyFree: 'Free reschedule up to 2 hours before',
  reviewPolicyFullRefund: '100% refund 4+ hours before',
  reviewPolicyHalfRefund: '50% within 4 hours',
  reviewPolicyNoRefund: 'No refund after start',
  reviewNotEmergency: 'What HelloHomeo does not do',
  reviewNotEmergencyBody:
    'HelloHomeo is not an emergency service. For emergencies, contact your nearest hospital.',
  reviewTotalAmount: 'Total Amount',
  reviewProceedPay: 'Proceed to pay',
  payTitle: 'Payment',
  paySlotHeld: 'Slot held for {time}',
  payConsultWith: 'Consultation with {name} · {when}',
  payViewBreakdown: 'View breakdown',
  payHideBreakdown: 'Hide breakdown',
  payMethod: 'Payment Method',
  payUpi: 'UPI',
  payGpay: 'Google Pay',
  payPhonePe: 'PhonePe',
  payPaytm: 'Paytm',
  payEnterUpi: 'Enter UPI ID',
  payUpiPlaceholder: 'name@upi',
  payCards: 'Credit & Debit Cards',
  paySavedCard: 'HDFC Bank Debit Card',
  paySavedCardMeta: 'Ending in 4821',
  paySavedBadge: 'Saved',
  payAddCard: '+ Add new debit or credit card',
  payNetbanking: 'Netbanking',
  paySelectBank: 'Select bank',
  payWallets: 'Wallets',
  payBankHdfc: 'HDFC Bank',
  payBankSbi: 'State Bank of India',
  payBankIcici: 'ICICI Bank',
  payWalletAmazon: 'Amazon Pay',
  payWalletMobikwik: 'Mobikwik',
  payPci: 'PCI-DSS Compliant',
  payNoStore: 'No card details stored',
  payRefunds: 'Refunds to original method',
  payCta: 'Pay {amount}',
  payStatusSecure: 'Secure Payment',
  payStatusSuccessTitle: 'Appointment confirmed',
  payStatusSuccessMeta: '{amount} paid · Payment ID {id}',
  payStatusHomeopath: 'Homeopath',
  payStatusDateTime: 'Date & Time',
  payStatusConsultType: 'Consultation Type',
  payStatusPatient: 'Patient',
  payStatusReminder:
    'We’ll remind you 24 hours and 30 minutes before. Join opens 10 minutes early.',
  payStatusAddCalendar: 'Add to calendar',
  payStatusViewAppointment: 'View appointment',
  payStatusReceipt: 'Download receipt',
  payStatusFailedTitle: 'Payment failed',
  payStatusFailedBody:
    'Your money was not deducted. If any amount was debited, it will be refunded within 5–7 working days.',
  payStatusReason: 'Reason',
  payStatusFailReason: 'Bank declined the transaction',
  payStatusAttempt: 'Attempt ID',
  payStatusHoldMore: 'Your {slot} slot is held for {time} more.',
  payStatusRetry: 'Retry payment',
  payStatusOtherMethod: 'Choose another method',
  payStatusOtherSlot: 'Choose a different slot',
  payStatusPendingTitle: 'Payment is processing',
  payStatusPendingBody:
    'Your bank is confirming this payment. This usually takes under 2 minutes — do not pay again.',
  payStatusInitiated: 'Initiated',
  payStatusBankConfirming: 'Bank confirming',
  payStatusConfirmed: 'Confirmed',
  payStatusCheck: 'Check status',
  payStatusSupport: 'Contact support',
  payStatusNotify: 'You’ll get an SMS and app notification once it’s confirmed.',
  doctorsBookings: 'Your bookings',
  doctorsWaitingAcceptance: 'Waiting for acceptance',
  doctorsNoBookings: 'No booking requests yet. Book a consultation to see it here.',
};
