import type { TranslationMap } from './types';

export const mr: TranslationMap = {
  appName: 'निगा पेशंट',
  brandName: 'हॅलोहोमिओ',
  tagline: 'सर्वांसाठी समग्र उपचार',
  byline: 'होमिओसेंट्रम तर्फे',
  welcomeHeadline: 'होमिओपॅथी.\nतुम्ही जिथे असाल तिथे.',
  chooseLanguageTitle: 'भाषा निवडा / Choose your language',
  languageNameMarathi: 'मराठी',
  languageNameEnglish: 'English',
  continueInMarathi: 'मराठीत सुरू ठेवा',
  continueInEnglish: 'Continue in English',
  continue: 'पुढे जा',
  teleconsultDisclaimer:
    'हॅलोहोमिओ ही टेलिकन्सलटेशन सेवा आहे. ही आपत्कालीन सेवा नाही.',
  skip: 'वगळा',
  onboardingSlide1Title: 'सत्यापित होमिओपॅथिक डॉक्टर शोधा',
  onboardingSlide1Body:
    'काळजीची गरज, भाषा, स्थान, शुल्क आणि उपलब्धतेनुसार शोधा. प्रत्येक डॉक्टरांची नोंदणी सत्यापित आहे.',
  onboardingSlide2Title: 'व्हिडिओ, ऑडिओ किंवा चॅटद्वारे सल्ला घ्या',
  onboardingSlide2Body:
    'घरातून कमी-डेटा कनेक्शनवर सामील व्हा. नेटवर्क कमकुवत असताना ऑडिओ पर्याय सल्ला सुरू ठेवतो.',
  onboardingSlide3Title: 'नोंदी, प्रिस्क्रिप्शन आणि औषधे एकाच ठिकाणी',
  onboardingSlide3Body:
    'तुमचे स्वाक्षरी केलेले प्रिस्क्रिप्शन, फॉलो-अप योजना आणि होमिओमेड्स डिलिव्हरी स्थिती, संपूर्ण कुटुंबासाठी जतन.',
  getStarted: 'सुरू करा',
  alreadyHaveAccount: 'माझे खाते आधीच आहे',
  signInTitle: 'तुमचा मोबाईल नंबर प्रविष्ट करा',
  signInSubtitle:
    'आम्ही पडताळणीसाठी ६-अंकी OTP पाठवू. तुमचा नंबर डॉक्टरांना कधीही दाखवला जाणार नाही.',
  mobileNumberPlaceholder: 'मोबाईल नंबर',
  countryCode: '+91',
  sendOtp: 'OTP पाठवा',
  orDivider: 'किंवा',
  bookViaHelpline: 'आमच्या हेल्पलाइनला कॉल करून बुक करा',
  helplineHint: 'मराठीत असिस्टेड बुकिंगसाठी — स्लो नेटवर्कवर उपयुक्त.',
  signInDisclaimer:
    'हॅलोहोमिओ ही होमिओसेंट्रम द्वारे टेलिकन्सल्टेशन सेवा आहे. ती आपत्कालीन सेवा प्रदान करत नाही.',
  invalidMobile: 'वैध १०-अंकी मोबाईल नंबर प्रविष्ट करा',
  whatsappConsent:
    'मी होमिओसेंट्रमकडून WhatsApp संदेश मिळवण्यास सहमत आहे.',
  whatsappConsentRequired:
    'कृपया होमिओसेंट्रमकडून WhatsApp संदेश मिळवण्यास सहमती द्या.',
  back: 'मागे',
  otpTitle: 'पडताळणी कोड प्रविष्ट करा',
  otpSubtitle: 'आम्ही तुमच्या फोन नंबरवर ६-अंकी कोड पाठवला आहे',
  otpDidntReceive: 'कोड मिळाला नाही?',
  verify: 'OTP पडताळा',
  resendOtp: 'OTP पुन्हा पाठवा',
  otpResendIn: 'कोड पुन्हा पाठवा',
  contactHelpline: 'हेल्पलाइनशी संपर्क साधा',
  getCodeWhatsApp: 'WhatsApp वर कोड मिळवा',
  otpNeedAssistance: 'मदत हवी आहे? सपोर्टशी संपर्क साधा',
  otpSupportEmail: 'care@hellohomeo.com',
  profileTitle: 'प्रोफाइल पूर्ण करा',
  profileStep: 'पायरी १/२',
  fullName: 'पूर्ण नाव',
  fullNamePlaceholder: 'तुमचे नाव प्रविष्ट करा',
  dateOfBirth: 'जन्म तारीख',
  dateOfBirthPlaceholder: 'dd/mm/yyyy',
  dateOfBirthHint: 'वयानुसार योग्य काळजी घेण्यासाठी वापरले जाते',
  gender: 'लिंग',
  genderFemale: 'स्त्री',
  genderMale: 'पुरुष',
  genderOther: 'इतर',
  preferredLanguage: 'निवडलेली भाषा',
  preferredLanguagePlaceholder: 'भाषा निवडा',
  languageHindi: 'हिंदी',
  cityTaluka: 'शहर / तालुका',
  cityTalukaPlaceholder: 'शहर / तालुका',
  address: 'पत्ता',
  addressPlaceholder: 'तुमचा पूर्ण पत्ता प्रविष्ट करा',
  state: 'राज्य',
  statePlaceholder: 'राज्य निवडा',
  alternateMobile: 'पर्यायी मोबाईल नंबर',
  email: 'ईमेल पत्ता',
  emailPlaceholder: 'example@mail.com',
  referredBy: 'यांच्याकडून संदर्भ मिळाला (पर्यायी)',
  referredByPlaceholder: 'डॉक्टर किंवा मित्राचे नाव',
  pincode: 'पिन कोड',
  pincodePlaceholder: 'पिन कोड',
  accessibilityNeeds: 'प्रवेशयोग्यता गरजा (पर्यायी)',
  preferAudioConsult: 'मला ऑडिओ सल्लामसलत आवडते',
  needLargeText: 'मला मोठ्या अक्षरांची गरज आहे',
  needCallAssistance: 'मला कॉलमध्ये सामील होण्यासाठी मदतीची आवश्यकता आहे',
  profilePrivacyNote:
    'फक्त तुमचे नाव, वय आणि तुम्ही सल्लामसलत दरम्यान शेअर केलेले तपशील तुमच्या डॉक्टरांना दिसतात. तुमचा मोबाईल नंबर मास्क केलेला राहतो.',
  skipForNow: 'आत्तासाठी वगळा',
  consentTitle: 'तुमची गोपनीयता आणि संमती',
  consentStep: 'पायरी २/२',
  consentIntro:
    'तुम्ही काय शेअर करता यावर तुमचे नियंत्रण आहे. खालील प्रत्येक परवानगी स्वतंत्र आहे — तुम्ही नंतर खाते > संमती केंद्र मध्ये त्या बंद करू शकता.',
  privacyNoticeVersion: 'गोपनीयता सूचना v1.2 · २८ ऑगस्ट २०२६ पासून प्रभावी',
  readFullNotice: 'पूर्ण सूचना वाचा',
  privacyNoticeTitle: 'गोपनीयता सूचना',
  consentRequired: 'आवश्यक',
  consentTeleconsultTitle: 'टेलिकन्सलटेशन',
  consentTeleconsultBody:
    'सत्यापित डॉक्टरांना ऑनलाइन सल्ला देण्यास आणि क्लिनिकल नोंदी करण्यास परवानगी द्या.',
  consentRecordsTitle: 'मी बुक केलेल्या डॉक्टरांसोबत आरोग्य नोंदी शेअर करा',
  consentRecordsBody:
    'तुमच्या डॉक्टरांना मागील प्रिस्क्रिप्शन आणि अपलोड केलेली कागदपत्रे पाहता येतात.',
  consentPharmacyTitle: 'औषध वितरण (HomeoMeds)',
  consentPharmacyBody:
    'परवानाधारक फार्मसीला ऑर्डर तयार करण्यासाठी आवश्यक असलेले प्रिस्क्रिप्शन तपशीलच शेअर करा.',
  consentUpdatesTitle: 'अपडेट्स आणि आरोग्य टिप्स',
  consentUpdatesBody:
    'WhatsApp, SMS किंवा ईमेलवर ऑफर्स, लेख आणि रिमाइंडर्स.',
  consentRecordingNote:
    'सल्लामसलतीचे रेकॉर्डिंग वेगळे विचारले जाते, फक्त सल्लामसलतीच्या वेळी.',
  agreeAndContinue: 'सहमत आणि पुढे जा',
  manageLater: 'नंतर व्यवस्थापित करा',
  close: 'बंद करा',
  done: 'पूर्ण',
  cancel: 'रद्द करा',
  familyMembersTitle: 'कुटुंबातील सदस्य',
  familyHelp: 'मदत',
  familyMembersYouManage: 'तुम्ही व्यवस्थापित करता ते सदस्य',
  familyAdultConfirmNote:
    '१८ वर्षे आणि त्यावरील सदस्यांनी स्वतःच्या मोबाईल नंबरवर पुष्टी केली पाहिजे, त्यानंतरच तुम्ही बुकिंग करू शकता किंवा नोंदी पाहू शकता.',
  familyAddMember: 'कुटुंबातील सदस्य जोडा',
  familyYouBadge: 'तुम्ही',
  familyGuardianBadge: 'पालक',
  familyPendingBadge: 'अधिकृतता प्रलंबित',
  familyAuthorizedBadge: 'अधिकृत',
  yearsShort: 'वर्षे',
  relationship: 'नाते',
  relationshipPlaceholder: 'नाते निवडा',
  relationshipSpouse: 'जोडीदार',
  relationshipChild: 'मूल',
  relationshipParent: 'आई-वडील',
  relationshipSibling: 'भावंड',
  relationshipOther: 'इतर',
  familyMobileHint: '१८ वर्षे आणि त्यावरील सदस्यांसाठी आवश्यक',
  familyManageConsent:
    'मी पुष्टी करतो की या व्यक्तीच्या आरोग्य नोंदी व्यवस्थापित करण्यासाठी मी अधिकृत आहे',
  familySendAuthRequest: 'अधिकृतता विनंती पाठवा',
  familyRemoveMember: 'सदस्य काढून टाका',
  familyMoreOptions: 'अधिक पर्याय',
  addFamilyMemberTitle: 'कुटुंबातील सदस्य जोडा',
  homeTitle: 'स्वागत आहे',
  homeSubtitle: 'निगा होमिओसेंट्रम',
  homeHello: 'नमस्कार',
  homeForWhom: 'कोणासाठी',
  homeForPrefix: 'साठी',
  homeForMyself: 'स्वतःसाठी',
  homeSearchPlaceholder: 'डॉक्टर किंवा काळजी गरजा शोधा',
  homeNextConsultation: 'पुढील सल्लामसलत',
  homeDoctorName: 'डॉ. अंजली देशमुख',
  homeDoctorQualification: 'B.H.M.S. - होमिओपॅथी तज्ञ',
  homeVerified: 'सत्यापित',
  homeConsultWhen: 'आज, संध्याकाळी ६:३० · व्हिडिओ',
  homeConsultDate: 'आज, संध्याकाळी ६:३०',
  homeConsultMode: 'व्हिडिओ',
  homeStartsIn: '४२ मिनिटांत सुरू',
  homeJoinConsultation: 'सल्लामसलत जॉईन करा',
  homeFollowUpDue: 'आरवसाठी फॉलो-अप देय आहे',
  homeFillSymptomDiary: 'लक्षण डायरी भरा',
  homeOrderNumber: 'ऑर्डर #HM-4821',
  homeOrderOutForDelivery: 'वितरणासाठी बाहेर पडली आहे',
  homeHomeoMedsOrder: 'होमओमेड्स ऑर्डर',
  homeTrack: 'ट्रॅक करा',
  homeQuickActions: 'त्वरित कृती',
  homeBookConsultation: 'सल्लामसलत बुक करा',
  homeInstantAdvice: 'आता सल्ला घ्या',
  homeInstantBadge: 'त्वरीत',
  homeMyPrescriptions: 'माझी प्रिस्क्रिप्शन्स',
  homeOrderMedicines: 'औषधे ऑर्डर करा',
  homeCareCategories: 'काळजी श्रेणी',
  homeViewAll: 'सर्व पहा',
  homeCatSkin: 'त्वचा',
  homeCatAllergy: 'ॲलर्जी आणि श्वसन',
  homeCatDigestion: 'पचन',
  homeCatWomensHealth: 'महिलांचे आरोग्य',
  homeCatChildCare: 'बालसंगोपन',
  homeHealthTips: 'आरोग्य टिप्स',
  homeTipCategory: 'जीवनशैली आणि जुने आजार',
  homeTipTitle: 'होमिओपॅथीसह रोगप्रतिकारक शक्ती कशी वाढवावी',
  homeTipExcerpt:
    'पावसाळ्यात निरोगी राहण्यासाठी साधे आणि नैसर्गिक उपाय. योग्य आहार आणि होमिओपॅथिक औषधांचा योग्य वापर...',
  homeTipReviewedBy: 'डॉ. एन. जामदार यांनी पुनरावलोकन केले',
  tipMinRead: '{count} मिनिट वाचन',
  tipSave: 'लेख जतन करा',
  tipSaved: 'जतन केले',
  tipShare: 'लेख शेअर करा',
  tipTextSize: 'अक्षराचा आकार',
  tipReviewedBy: '{name} यांनी पुनरावलोकन केले',
  tipReadReviewNotes: 'पुनरावलोकन टिपा वाचा',
  tipHideReviewNotes: 'पुनरावलोकन टिपा लपवा',
  tipDailyCare: 'दैनंदिन काळजी टिप्स',
  tipDisclaimerTitle: 'हा लेख काय नाही:',
  tipDisclaimerBody:
    'हे सामान्य शिक्षण आहे. हे निदान, प्रिस्क्रिप्शन किंवा नोंदणीकृत होमिओपॅथिक वैद्याच्या सल्ल्याची जागा नाही.',
  tipTalkToDoctor: 'याबद्दल डॉक्टरांशी बोला',
  tipTalkToDoctorBody: 'तुमच्या मुलाच्या लक्षणांनुसार वैयक्तिक सल्ला घ्या.',
  tipFindSkinDoctor: 'त्वचा-काळजी डॉक्टर शोधा',
  tipFindAllergyDoctor: 'ॲलर्जी डॉक्टर शोधा',
  tipFindLifestyleDoctor: 'डॉक्टर शोधा',
  tipRelatedReading: 'संबंधित वाचन',
  tipHelpful: 'हा लेख उपयुक्त होता का?',
  tipReport: 'चुकीची माहिती कळवा',
  tipCatRespiratory: 'श्वसन',
  tipCatWellness: 'वेलनेस',
  tipEczemaTitle: 'मुलांमधील एक्जिमा — होमिओपॅथिक काळजीतून काय अपेक्षित',
  tipEczemaExcerpt:
    'खाज आणि जळजळ असलेल्या त्वचेसाठी सौम्य, संपूर्ण-मूल काळजी — आणि सल्लामसलत कशी असते.',
  tipEczemaAuthorCreds: 'बी.एच.एम.एस., एम.डी. • नोंदणी: HGM-2453',
  tipEczemaReviewer: 'डॉ. निखिल बोंदर',
  tipEczemaPublished: 'प्रकाशित आणि पुनरावलोकन १२ ऑगस्ट २०२४',
  tipEczemaReviewNotes:
    'वैद्यकीय अचूकता आणि सोप्या भाषेसाठी पुनरावलोकन. वैयक्तिक उपचार नेहमी मुलाच्या पूर्ण केसवर आधारित असतो, केवळ या लेखावर नाही.',
  tipEczemaH1: 'बालपण एक्जिमा समजून घेणे',
  tipEczemaP1:
    'एक्जिमा (अॅटॉपिक डर्मेटायटिस) मुलांमध्ये सामान्य आहे. त्वचा कोरडी, खाजणारी आणि सहज जळजळ होते. फ्लेअर्स ये-जा करतात. होमिओपॅथिक सल्लामसलत झोप, पचन, मनःस्थिती, कौटुंबिक इतिहास आणि खाज कशाने वाढते-कमी होते हे पाहते — केवळ त्वचेवरील ठिपके नाही.',
  tipEczemaQuote:
    'होमिओपॅथी मुलाला संपूर्णपणे पाहते, केवळ त्वचा स्थिती नाही. आम्ही अंतर्गत संवेदनशीलता समजून घेण्याचा प्रयत्न करतो.',
  tipEczemaCheck1: 'पर्यावरण — उष्णता, धूळ, परागकण आणि कोरडी हवा फ्लेअर वाढवू शकतात.',
  tipEczemaCheck2: 'चिडवणारे — तीव्र साबण, लोकर आणि वारंवार सॅनिटायझर त्वचा कोरडी करतात.',
  tipEczemaCheck3: 'तणाव — कमी झोप, परीक्षा किंवा घरगुती अस्वस्थता खाज वाढवू शकते.',
  tipEczemaH2: 'होमिओपॅथिक दृष्टिकोन',
  tipEczemaP2:
    'उद्देश कालांतराने संवेदनशीलता कमी करणे आहे, केवळ खाज दाबणे नाही. नोंदणीकृत वैद्य सविस्तर केस घेतो, त्या मुलासाठी औषध निवडतो आणि झोप, मनःस्थिती व त्वचा कशी बदलते ते पाहतो. दैनंदिन त्वचा काळजी महत्त्वाचीच राहते.',
  tipEczemaCare1: 'आंघोळ थोडी आणि कोमट ठेवा — गरम पाणी त्वचेतील तेल काढते.',
  tipEczemaCare2: 'त्वचा हळूवार पुसून वाळवा. घासू नका.',
  tipEczemaCare3: 'त्वचा थोडी ओलसर असताना मॉइश्चराइझ करा.',
  tipEczemaCare4: 'सुती कपडे निवडा; तीव्र साबण आणि सुगंध टाळा.',
  tipAllergyTitle: 'मुलांच्या ॲलर्जी आणि ट्रिगर समजून घेणे',
  tipAllergyExcerpt:
    'वारंवार सर्दी, शिंकणे आणि हंगामी फ्लेअर्सकडे होमिओपॅथिक काळजी कशी पाहते.',
  tipAllergyPublished: 'प्रकाशित आणि पुनरावलोकन ४ ऑगस्ट २०२४',
  tipAllergyReviewNotes:
    'शैक्षणिक अचूकतेसाठी पुनरावलोकन. श्वास घेण्यास त्रास किंवा अचानक सूज ही तातडीची स्थिती डॉक्टराने तपासावी.',
  tipAllergyH1: 'वारंवार सर्दी नेहमी “केवळ विषाणू” नसते',
  tipAllergyP1:
    'अनेक मुले दर हंगामात शिंकतात, घरघर करतात किंवा नाक बंद होते. धूळ, परागकण आणि हवामान बदल सामान्य ट्रिगर आहेत. होमिओपॅथिक केसमध्ये झोप, आहार आणि एपिसोड्समधील पुनर्प्राप्तीही नोंदवली जाते.',
  tipAllergyQuote:
    'आम्ही ॲलर्जी होणाऱ्या मुलावर उपचार करतो, केवळ त्या दिवसाच्या शिंक्यावर नाही.',
  tipAllergyH2: 'सल्लामसलतीत काय अपेक्षित',
  tipAllergyP2:
    'फ्लेअर्सची साधी डायरी आणा — वेळ, अन्न, धूळ आणि झोप. दुसऱ्या डॉक्टरने दिलेला इनहेलर किंवा आपत्कालीन योजना सुरू ठेवण्यास सांगितले जाऊ शकते.',
  tipAllergyCare1: 'बिछाना आणि मऊ खेळणी नियमित धुवा.',
  tipAllergyCare2: 'मुलाची खोली हवा खेळती आणि धूरमुक्त ठेवा.',
  tipAllergyCare3: 'कोणते अन्न किंवा हवामान फ्लेअर सुरू करते ते नोंदवा.',
  tipImmunityPublished: 'प्रकाशित आणि पुनरावलोकन २८ जुलै २०२४',
  tipImmunityReviewer: 'डॉ. एन. जामदार',
  tipImmunityReviewNotes:
    'केवळ जीवनशैली मार्गदर्शन. तीव्र ताप, श्वास त्रास किंवा खूप आजारी मूल तातडीने तपासावे.',
  tipImmunityH1: 'पुनर्प्राप्तीला मदत करणाऱ्या छोट्या सवयी',
  tipImmunityP1:
    'झोप, कोमट घरगुती जेवण आणि न घाईचे खेळ पूरक गोष्टींपेक्षा जास्त मदत करतात. होमिओपॅथिक औषधे व्यक्तीनुसार निवडली जातात; लसी किंवा आपत्कालीन काळजीची जागा नाहीत.',
  tipImmunityQuote:
    'रोगप्रतिकार म्हणजे मुलाची प्रतिसाद पद्धत — आम्ही ती पद्धत आधार देतो, जबरदस्ती करत नाही.',
  tipImmunityP2:
    'पावसाळ्यात पाय कोरडे ठेवा, जेवण नियमित ठेवा आणि सर्दी सुरू होताच विश्रांती घ्या. केस घेतल्यानंतर वैद्य औषध योग्य आहे का ते सांगू शकतात.',
  tipImmunityCare1: 'आठवड्याच्या शेवटीही झोपेची वेळ नियमित ठेवा.',
  tipImmunityCare2: 'पॅकेज्ड स्नॅक्सऐवजी कोमट, साधे जेवण द्या.',
  tipImmunityCare3: 'हल्की सर्दी विश्रांती आणि द्रवपदार्थांसह चालू द्या, डॉक्टर अन्यथा सांगितल्याशिवाय.',
  homeTabHome: 'मुख्य',
  homeTabDoctors: 'डॉक्टर',
  homeTabRecords: 'रेकॉर्ड्स',
  homeTabMedicines: 'औषधे',
  homeTabAccount: 'खाते',
  homeNotifications: 'सूचना',
  homeComingSoon: 'लवकरच येत आहे',
  searchDoctorsTitle: 'डॉक्टर शोधा',
  searchPlaceholder: 'डॉक्टरांचे नाव, काळजी गरज किंवा ठिकाण',
  searchVoice: 'आवाजाने शोधा',
  searchListening: 'ऐकत आहे…',
  searchVoicePermissionDenied:
    'आवाजाने शोधण्यासाठी मायक्रोफोन आणि स्पीच परवानगी द्या.',
  searchVoiceUnavailable: 'या डिव्हाइसवर आवाजाने शोध उपलब्ध नाही.',
  searchVoiceLanguageUnsupported: 'या भाषेसाठी आवाजाने शोध उपलब्ध नाही.',
  searchRecentHeading: 'अलीकडील शोध',
  searchRecentSkin: 'त्वचेच्या तक्रारी',
  searchRecentDoctor: 'डॉ. देशमुख',
  searchRecentChild: 'सोलापुरात बालसंगोपन',
  searchRemoveRecent: 'काढा',
  searchTalkNow: 'उपलब्ध डॉक्टरांशी आता बोला',
  searchTypicalWait: 'सामान्य प्रतीक्षा ४–८ मिनिटे',
  searchSeeAvailability: 'उपलब्धता पहा',
  searchBrowseCareNeed: 'काळजी गरजेनुसार पहा',
  searchCareSkin: 'त्वचेच्या तक्रारी',
  searchCareSkinHint: 'एक्झिमा, मुरुम, केस',
  searchCareAllergy: 'ॲलर्जी आणि श्वसन',
  searchCareAllergyHint: 'सर्दी, दमा, सायनस',
  searchCareDigestive: 'पचनाची काळजी',
  searchCareDigestiveHint: 'आम्लपित्त, IBS, भूक',
  searchCareWomen: 'महिलांचे आरोग्य',
  searchCareWomenHint: 'चक्र, रजोनिवृत्ती, PCOS',
  searchCareChild: 'बालसंगोपन',
  searchCareChildHint: 'वाढ, रोगप्रतिकार, पोटदुखी',
  searchCarePain: 'वेदना आणि सांधे',
  searchCarePainHint: 'पाठ, गुडघा, संधिवात',
  searchCareLifestyle: 'जीवनशैली आणि जुने आजार',
  searchCareLifestyleHint: 'झोप, ताण, थायरॉइड',
  searchCareDisclaimer:
    'काळजी गरजांमुळे योग्य डॉक्टर सापडतात. हे निदान नाहीत.',
  searchNearYou: 'तुमच्या जवळ',
  searchLocation: 'स्थान',
  searchDoctorOpen: 'डॉक्टर पहा',
  searchCitySolapur: 'सोलापूर',
  searchCityPune: 'पुणे',
  searchCityMumbai: 'मुंबई',
  searchDoctorJoshiName: 'डॉ. ए. जोशी',
  searchDoctorJoshiMeta: 'BHMS • १५ वर्षे अनुभव',
  searchDoctorJoshiPlace: 'सोलापूर उत्तर • २.५ किमी',
  searchDoctorPatilName: 'डॉ. एस. पाटील',
  searchDoctorPatilMeta: 'BHMS • १२ वर्षे अनुभव',
  searchDoctorPatilPlace: 'सोलापूर पूर्व • ४.१ किमी',
  searchResultsTitle: 'शोध निकाल',
  searchFilters: 'फिल्टर',
  searchSortRelevance: 'क्रम: सुसंगतता',
  searchFilterVideo: 'व्हिडिओ',
  searchFilterMarathi: 'मराठी',
  searchFilterAvailableToday: 'आज उपलब्ध',
  searchFilterUnder500: '₹५०० पेक्षा कमी',
  searchResultsCount: '१८ सत्यापित डॉक्टर',
  searchResultsWhyOrder: 'हा क्रम का?',
  searchResultsWhyOrderBody:
    'निकाल सुसंगतता, उपलब्धता आणि सत्यापनावर आधारित आहेत. सशुल्क जागा Sponsored म्हणून दाखवल्या जातात आणि क्रम किंवा रेफरल बदलत नाहीत.',
  searchLangMarathi: 'मराठी',
  searchLangEnglish: 'इंग्रजी',
  searchLangHindi: 'हिंदी',
  searchModeVideo: 'व्हिडिओ',
  searchModeClinic: 'क्लिनिक',
  searchSponsored: 'प्रायोजित',
  searchPaidPlacement:
    'सशुल्क जागा. क्रम आणि रेफरल यावर परिणाम होत नाही.',
  searchCertifiedBanner:
    'होमिओसेंट्रम प्रमाणित फोकस प्रॅक्टिशनर — त्वचा काळजी',
  searchBook: 'बुक करा',
  searchConsultation: 'सल्लामसलत',
  searchResultAnjaliName: 'डॉ. अंजली देशमुख',
  searchResultAnjaliCredentials:
    'बी.एच.एम.एस., एम.डी. (होमिओपॅथी) — प्रॅक्टिस ऑफ मेडिसिन',
  searchResultAnjaliReg: 'नोंदणी MH-HOM-24581',
  searchResultAnjaliExperience: '१२ वर्षे अनुभव · सोलापूर',
  searchResultAnjaliReviews: '(२१२ समीक्षा)',
  searchResultAnjaliFee: '₹६००',
  searchResultAnjaliWhen: 'आज सायं. ६:३०',
  searchResultRajeshName: 'डॉ. राजेश पाटील',
  searchResultRajeshCredentials: 'बी.एच.एम.एस.',
  searchResultRajeshExperience: '८ वर्षे अनुभव · पुणे',
  searchResultRajeshReviews: '(८५ समीक्षा)',
  searchResultRajeshFee: '₹४००',
  searchResultRajeshWhen: 'उद्या सकाळी १०:००',
  searchResultSunitaName: 'डॉ. सुनीता शर्मा',
  searchResultSunitaCredentials: 'एम.डी. त्वचाविज्ञान',
  searchResultSunitaExperience: '१५ वर्षे अनुभव · मुंबई',
  searchResultSunitaReviews: '(५४० समीक्षा)',
  searchResultSunitaFee: '₹८००',
  searchResultSunitaWhen: '३० मिनिटांत उपलब्ध',
  searchResultsEmptyTitle: 'या फिल्टरशी जुळणारे सत्यापित डॉक्टर नाहीत',
  searchResultsEmptyBody:
    'तुमच्या गरजांनुसार सध्या कोणतेही प्रॅक्टिशनर सापडले नाहीत. शोध बदला किंवा काही फिल्टर काढून टाका.',
  searchResultsClearFilters: 'सर्व फिल्टर काढा',
  searchResultsBookAssistance: 'मदतीने बुक करा',
  searchResultsHelplinePrefix: 'तातडीची काळजी? हेल्पलाइन: ',
  searchResultsHelplineNumber: '१०४',
  searchAllFilters: 'सर्व फिल्टर',
  searchFilterSpecialty: 'विशेषता: त्वचाविज्ञान',
  searchFilterAvailabilityTodayLabel: 'उपलब्धता: आज',
  searchFilterLanguageMarathi: 'भाषा: मराठी',
  searchSortDistance: 'क्रम: अंतर',
  filterResetAll: 'सर्व रिसेट करा',
  filterCareNeed: 'काळजीची गरज',
  filterConsultMode: 'सल्ला देण्याची पद्धत',
  filterModeAudio: 'ऑडिओ',
  filterModeChat: 'चॅट',
  filterModeClinicVisit: 'क्लिनिक भेट',
  filterAvailability: 'उपलब्धता',
  filterAvailableNow: 'आता उपलब्ध',
  filterToday: 'आज',
  filterTomorrow: 'उद्या',
  filterSelectDate: 'तारीख निवडा',
  filterFeeRange: 'शुल्काची व्याप्ती',
  filterFeeUnder500: '₹५०० च्या आत',
  filterFee500to1000: '₹५००–₹१०००',
  filterFeeMin: '₹२००',
  filterFeeMax: '₹२,०००',
  filterDoctorSection: 'डॉक्टर',
  filterQualifications: 'पात्रता आणि प्रमाणपत्रे',
  filterRecognizedQual: 'मान्यताप्राप्त पात्रता',
  filterFocusCert: 'होमिओसेंट्रम फोकस प्रमाणपत्र',
  filterLocation: 'ठिकाण',
  filterLocationPlaceholder: 'शहर किंवा परिसर शोधा',
  filterCurrentLocation: 'माझे वर्तमान ठिकाण',
  filterResultsDisclaimer:
    'तुमचे शोध परिणाम डॉक्टरांच्या उपलब्धतेनुसार आणि तुमच्या शोध निकषांनुसार क्रमवारी लावले जातात.',
  filterShowDoctors: '{count} डॉक्टर दाखवा',
  filterClear: 'क्लियर करा',
  profileShare: 'शेअर करा',
  profileSave: 'जतन करा',
  profileSaved: 'जतन केले',
  profileTabAbout: 'विषयी',
  profileTabCredentials: 'पात्रता',
  profileTabReviews: 'समीक्षा',
  profileTabAvailability: 'उपलब्धता',
  profileVerifiedBy: 'होमिओसेंट्रम द्वारे सत्यापित',
  profileQualVerified: 'पात्रता सत्यापित',
  profileLicensed: 'सध्या प्रॅक्टिस करण्याची परवाना आहे',
  profileViewDetails: 'तपशील पहा',
  profileReadMore: 'अधिक वाचा',
  profileReadLess: 'कमी दाखवा',
  profileCareFocus: 'काळजी फोकस',
  profileCareFocusNote:
    'हा डॉक्टर सामान्यतः या काळजी गरजांवर उपचार करतो. हे निदान किंवा निकालाची हमी नाही.',
  profileConsultations: 'सल्लामसलत',
  profileVideoConsult: 'व्हिडिओ सल्लामसलत',
  profileAudioConsult: 'ऑडिओ सल्लामसलत',
  profileFollowUpChat: 'फॉलो-अप चॅट',
  profileFollowUpChatHint:
    'खिडकी या डॉक्टरांच्या सध्याच्या सेवा योजनेनुसार ठरते आणि तुम्ही पैसे देण्यापूर्वी दाखवली जाते.',
  profileIncluded: 'समाविष्ट',
  profileClinicVisit: 'क्लिनिक भेट',
  profileConsultationFee: 'सल्ला शुल्क',
  profileBookConsultation: 'सल्लामसलत बुक करा',
  profileDetailsTitle: 'सत्यापन तपशील',
  profileLanguagesSpoken: 'बोलल्या जाणाऱ्या भाषा',
  profileNoSlots: 'सध्या दाखवण्यासाठी अधिक स्लॉट नाहीत.',
  credAndVerification: 'पात्रता आणि सत्यापन',
  credRecognisedTitle: 'मान्यताप्राप्त वैद्यकीय पात्रता',
  credRecognisedNote:
    'राष्ट्रीय होमिओपॅथी आयोगांतर्गत मान्यताप्राप्त पात्रता.',
  credVerified: 'सत्यापित',
  credLicensedBadge: 'सध्या परवानाधारक',
  credStatusActive: 'स्थिती: सक्रिय',
  credFocusTitle: 'होमिओसेंट्रम फोकस प्रमाणपत्रे',
  credFocusWarning:
    'ही होमिओसेंट्रम व्यावसायिक-विकास प्रमाणपत्रे आहेत. ही मान्यताप्राप्त वैद्यकीय विशेषज्ञता नाहीत आणि डॉक्टराला विशेषज्ञ बनवत नाहीत.',
  credActive: 'सक्रिय',
  credVerifyCertificate: 'प्रमाणपत्र सत्यापित करा',
  credCareLinkTitle: 'केअरलिंक नेटवर्क भूमिका',
  credCareLinkNote:
    'होमिओसेंट्रम नेटवर्कमधील अंतर्गत रेफरल आणि जबाबदारी पातळी. ही वैद्यकीय पात्रता किंवा सार्वजनिक विशेषज्ञ पदवी नाही.',
  credSomethingWrong: 'काही चुकीचे दिसते का?',
  credReportsGoTo: 'तक्रारी होमिओसेंट्रम क्लिनिकल गव्हर्नन्सकडे जातात.',
  credReportError: 'प्रोफाइल त्रुटी कळवा',
  credReportProfileLink: 'Report Profile | प्रोफाईल तक्रार करा',
  credPrivacyLink: 'Privacy Policy | गोपनीयता धोरण',
  credNetworkCopyright: 'Verified Homeopathy Network © 2024',
  credAnjaliMdTitle: 'एम.डी. (होमिओपॅथी) — प्रॅक्टिस ऑफ मेडिसिन',
  credAnjaliMdDetail: 'शासकीय होमिओपॅथिक मेडिकल कॉलेज, पुणे · २०१६',
  credAnjaliMdBadge: '१२ ऑगस्ट २०२६ रोजी सत्यापित',
  credAnjaliBhmsTitle: 'बी.एच.एम.एस.',
  credAnjaliBhmsDetail: 'महाराष्ट्र आरोग्य विज्ञान विद्यापीठ · २०१२',
  credAnjaliRegTitle: 'नोंदणी क्र. MH-HOM-24581',
  credAnjaliCouncil: 'परिषद: महाराष्ट्र होमिओपॅथी परिषद',
  credAnjaliValid: 'वैधता: ३१ मार्च २०२८ पर्यंत',
  credAnjaliFocusTitle: 'होमिओसेंट्रम सर्टिफाइड फोकस प्रॅक्टिशनर — त्वचा काळजी',
  credAnjaliFocusId: 'प्रमाणपत्र आयडी HC-FP-SKN-0912 · जारी ०४ फेब्रुवारी २०२६',
  credAnjaliFocusValid: 'वैधता ०४ फेब्रुवारी २०२९ पर्यंत',
  credAnjaliCareLinkTitle: 'जिल्हा सल्लागार · केअरलिंक',
  credAnjaliCareLinkQuote:
    '“तालुका आणि नेटवर्क डॉक्टरांकडून रेफर केलेल्या प्रकरणांचे पुनरावलोकन.”',
  credRajeshBhmsTitle: 'बी.एच.एम.एस.',
  credRajeshBhmsDetail: 'महाराष्ट्र आरोग्य विज्ञान विद्यापीठ · २०१६',
  credRajeshRegTitle: 'नोंदणी क्र. MH-HOM-18820',
  credRajeshValid: 'वैधता: ३१ मार्च २०२७ पर्यंत',
  credRajeshFocusTitle:
    'होमिओसेंट्रम सर्टिफाइड फोकस प्रॅक्टिशनर — वेदना आणि जीवनशैली',
  credRajeshFocusId: 'प्रमाणपत्र आयडी HC-FP-PAIN-0440 · जारी १० जानेवारी २०२६',
  credRajeshFocusValid: 'वैधता १० जानेवारी २०२९ पर्यंत',
  credRajeshCareLinkTitle: 'नेटवर्क डॉक्टर · केअरलिंक',
  credRajeshCareLinkQuote:
    '“प्रथम-स्तरीय होमिओपॅथिक काळजी आणि गुंतागुंतीची प्रकरणे रेफर.”',
  credSunitaMdTitle: 'एम.डी. (होमिओपॅथी) — प्रॅक्टिस ऑफ मेडिसिन',
  credSunitaMdDetail: 'शासकीय होमिओपॅथिक मेडिकल कॉलेज, मुंबई · २०११',
  credSunitaMdBadge: '१८ ऑगस्ट २०२६ रोजी सत्यापित',
  credSunitaBhmsTitle: 'बी.एच.एम.एस.',
  credSunitaBhmsDetail: 'महाराष्ट्र आरोग्य विज्ञान विद्यापीठ · २००८',
  credSunitaRegTitle: 'नोंदणी क्र. MH-HOM-10214',
  credSunitaValid: 'वैधता: ३१ मार्च २०२८ पर्यंत',
  credSunitaFocusTitle: 'होमिओसेंट्रम सर्टिफाइड फोकस प्रॅक्टिशनर — त्वचा काळजी',
  credSunitaFocusId: 'प्रमाणपत्र आयडी HC-FP-SKN-0718 · जारी २२ मार्च २०२६',
  credSunitaFocusValid: 'वैधता २२ मार्च २०२९ पर्यंत',
  credSunitaCareLinkTitle: 'जिल्हा सल्लागार · केअरलिंक',
  credSunitaCareLinkQuote:
    '“नेटवर्क डॉक्टरांकडून त्वचा-काळजी रेफरलचे पुनरावलोकन.”',
  profileAnjaliExp: '१२ वर्षे अनुभव',
  profileAnjaliConsults: '१,८४० सल्लामसलत',
  profileAnjaliAbout:
    'डॉ. अंजली देशमुख एक दशकभराहून अधिक अनुभव असलेल्या समर्पित होमिओपॅथिक वैद्य आहेत. त्या आजाराचे मूळ कारण समजून घेण्यावर भर देतात, केवळ लक्षणे दाबण्यावर नाही. त्यांच्या सौम्य आणि सहानुभूतीपूर्ण वागण्यामुळे प्रत्येक रुग्ण ऐकला आणि काळजी घेतला जातो.',
  profileAnjaliRegVerified: 'नोंदणी MH-HOM-24581 सत्यापित',
  profileAnjaliLastVerified: 'शेवटचे सत्यापन १२ ऑगस्ट २०२६',
  profileAnjaliNext: 'पुढील उपलब्ध बुध, २६ ऑगस्ट, सायं. ६:३०',
  profileAnjaliClinicFee: '₹५००',
  profileRajeshExp: '८ वर्षे अनुभव',
  profileRajeshConsults: '६४० सल्लामसलत',
  profileRajeshAbout:
    'डॉ. राजेश पाटील पुण्यातील कुटुंबांसाठी रोजच्या होमिओपॅथिक काळजीवर भर देतात. सल्ला स्पष्ट आणि व्यावहारिक ठेवतात आणि घरी उपचार सुरू राहतील यासाठी फॉलो-अप करतात.',
  profileRajeshRegVerified: 'नोंदणी सत्यापित',
  profileRajeshLastVerified: 'शेवटचे सत्यापन ४ ऑगस्ट २०२६',
  profileRajeshNext: 'पुढील उपलब्ध उद्या सकाळी १०:००',
  profileSunitaExp: '१५ वर्षे अनुभव',
  profileSunitaConsults: '३,१२० सल्लामसलत',
  profileSunitaAbout:
    'डॉ. सुनीता शर्मा मुंबईतील त्वचा-केंद्रित होमिओपॅथिक प्रॅक्टिशनर आहेत. दीर्घकाळच्या त्वचा तक्रारींसाठी शांत, टप्प्याटप्प्याने योजना देतात.',
  profileSunitaRegVerified: 'नोंदणी सत्यापित',
  profileSunitaLastVerified: 'शेवटचे सत्यापन १८ ऑगस्ट २०२६',
  profileSunitaNext: 'पुढील उपलब्ध ३० मिनिटांत',
  profileSunitaClinicFee: '₹७००',
  profileReview1Name: 'प्रिया के.',
  profileReview1Body:
    'काळजीपूर्वक ऐकले आणि योजना सोप्या शब्दांत सांगितली. फॉलो-अपनंतर त्वचा खूप शांत आहे.',
  profileReview1Date: '२ आठवड्यांपूर्वी',
  profileReview2Name: 'संजय एम.',
  profileReview2Body:
    'वेळेवर व्हिडिओ सल्ला. आहार आणि औषधांबाबत स्पष्ट मार्गदर्शन. पुन्हा बुक करेन.',
  profileReview2Date: '१ महिन्यापूर्वी',
  doctorsTabSubtitle: 'तुमच्या जवळचे सत्यापित होमिओपॅथी डॉक्टर शोधा',
  languageLabel: 'भाषा',
  english: 'इंग्रजी',
  marathi: 'मराठी',
  loading: 'लोड होत आहे',
  splashLoadingEn: 'LOADING...',
  splashLoadingMr: 'लोड होत आहे...',
  networkError: 'कनेक्ट करता आले नाही. तुमचे इंटरनेट तपासा.',
  genericError: 'काहीतरी चुकले. कृपया पुन्हा प्रयत्न करा.',
  emptyState: 'सध्या दाखवण्यासाठी काहीही नाही.',
  retry: 'पुन्हा प्रयत्न करा',
  accountEditProfile: 'प्रोफाइल संपादा',
  accountSectionMyCare: 'माझी काळजी',
  accountFamilyMembers: 'कुटुंबातील सदस्य',
  accountFamilyMembersBadge: '४ सदस्य',
  accountAppointments: 'माझ्या भेटी',
  accountPrescriptions: 'माझी प्रिस्क्रिप्शन्स',
  accountHealthRecords: 'आरोग्य नोंदी',
  accountHealthInsights: 'आरोग्य अंतर्दृष्टी',
  accountPainPoints: 'वेदना बिंदू',
  accountReminders: 'स्मरणपत्रे',
  accountRemindersBadge: '६ सक्रिय',
  accountCareLink: 'केअरलिंक रेफरल',
  accountCareLinkBadge: '१ सक्रिय',
  accountSectionWellness: 'वेलनेस',
  accountNonClinical: 'गैर-वैद्यकीय',
  accountAstroWellness: 'अॅस्ट्रो-वेलनेस',
  accountAstroHelper: 'पर्यायी पारंपरिक मार्गदर्शन. वैद्यकीय सल्ला नाही.',
  accountBirthDetails: 'जन्म तपशील',
  accountSectionPreferences: 'प्राधान्ये',
  accountAccessibility: 'सुलभता',
  accountAccessibilityValue: 'मोठे अक्षर चालू',
  accountLowDataMode: 'कमी-डेटा मोड',
  accountLowDataHelper:
    'आधी मजकूर दाखवतो आणि प्रतिमा वगळतो. मंद नेटवर्कवर शिफारस.',
  accountSectionPayments: 'देयके',
  accountPaymentMethods: 'पेमेंट पद्धती',
  accountPaymentMethodsBadge: '२ जतन',
  accountPaymentsReceipts: 'देयके आणि पावत्या',
  accountMembership: 'सदस्यत्व',
  accountComingSoon: 'लवकरच',
  accountSectionPrivacy: 'गोपनीयता आणि सुरक्षा',
  accountConsentCentre: 'संमती केंद्र',
  accountConsentBadge: '५ परवानग्या',
  accountDataRequests: 'माझ्या डेटा विनंत्या',
  accountLoginActivity: 'लॉगिन क्रिया',
  accountLoginActivityBadge: '३ डिव्हाइस',
  accountDownloadData: 'माझा डेटा डाउनलोड करा',
  accountSectionHelp: 'मदत',
  accountHelpCentre: 'मदत केंद्र',
  accountSupportTickets: 'माझ्या सपोर्ट तिकिटे',
  accountSupportTicketsBadge: '१ उघडे',
  accountAbout: 'हॅलोहोमिओ बद्दल',
  accountTerms: 'वापर अटी',
  accountPrivacyNotice: 'गोपनीयता सूचना',
  accountPrivacyNoticeVersion: 'v1.2',
  accountLogOut: 'लॉग आउट',
  accountDeleteAccount: 'माझे खाते हटवा',
  accountDeleteAccountNote:
    'काही नोंदी कायद्याने हटवल्यानंतरही ठेवाव्या लागतात — का आणि काय ते आम्ही समजावून सांगू.',
  bookTitle: 'भेट बुक करा',
  bookMore: 'अधिक',
  bookConsultingFor: 'सल्ला यांच्यासाठी:',
  bookMode: 'सल्ला पद्धत',
  bookVideo: 'व्हिडिओ',
  bookAudio: 'ऑडिओ',
  bookClinic: 'क्लिनिक',
  bookSelectDate: 'दिनांक निवडा',
  bookSelectMonth: 'महिना निवडा',
  bookAugust: 'ऑगस्ट',
  bookToday: 'आज',
  bookWed: 'बुध',
  bookThu: 'गुरु',
  bookFri: 'शुक्र',
  bookSat: 'शनि',
  bookSun: 'रवि',
  bookMon: 'सोम',
  bookTue: 'मंगळ',
  bookSlots: 'उपलब्ध स्लॉट',
  bookMorning: 'सकाळ',
  bookAfternoon: 'दुपार',
  bookEvening: 'संध्याकाळ',
  bookSlotsCount: '{count} स्लॉट',
  bookTimezone: 'सर्व वेळा IST (भारतीय प्रमाणवेळ) मध्ये दाखवल्या आहेत',
  bookSummary: 'निवड सारांश',
  bookWhoFor: 'हे कोणासाठी आहे?',
  bookMyself: 'स्वतः',
  bookAddMember: 'कुटुंबातील सदस्य जोडा',
  bookAaravMeta: '६ वर्षे • मुलगा',
  bookMeeraMeta: '३१ वर्षे • पती/पत्नी',
  bookMonthJan: 'जानेवारी',
  bookMonthFeb: 'फेब्रुवारी',
  bookMonthMar: 'मार्च',
  bookMonthApr: 'एप्रिल',
  bookMonthMay: 'मे',
  bookMonthJun: 'जून',
  bookMonthJul: 'जुलै',
  bookMonthAug: 'ऑगस्ट',
  bookMonthSep: 'सप्टेंबर',
  bookMonthOct: 'ऑक्टोबर',
  bookMonthNov: 'नोव्हेंबर',
  bookMonthDec: 'डिसेंबर',
  bookWaitlistTitle: '{date} चे सर्व स्लॉट भरले',
  bookWaitlistBody:
    'स्लॉट मोकळा झाल्यास आम्ही ऑफर करू. ऑफर ३० मिनिटांत संपते.',
  bookJoinWaitlist: 'वेटलिस्ट जॉइन करा',
  bookWaitlistSummary: 'वेटलिस्ट · {date}',
  bookAnjaliShortCreds: 'बी.एच.एम.एस., एम.डी. (होम.)',
  bookRajeshShortCreds: 'बी.एच.एम.एस.',
  bookSunitaShortCreds: 'एम.डी. (होमिओपॅथी)',
  bookSlot0900: '०९:०० AM',
  bookSlot0930: '०९:३० AM',
  bookSlot1000: '१०:०० AM',
  bookSlot1030: '१०:३० AM',
  bookSlot1100: '११:०० AM',
  bookSlot1130: '११:३० AM',
  bookSlot1300: '०१:०० PM',
  bookSlot1330: '०१:३० PM',
  bookSlot1400: '२:०० PM',
  bookSlot1430: '०२:३० PM',
  bookSlot1530: '३:३० PM',
  bookSlot1700: '५:०० PM',
  bookSlot1800: '६:०० PM',
  bookSlot1830: '६:३० PM',
  bookSlot1900: '७:०० PM',
  bookSlot1930: '७:३० PM',
  bookSummaryWed26: 'बुध, २६ ऑगस्ट २०२६',
  bookSummaryThu27: 'गुरु, २७ ऑगस्ट २०२६',
  bookSummaryFri28: 'शुक्र, २८ ऑगस्ट २०२६',
  bookSummarySat29: 'शनि, २९ ऑगस्ट २०२६',
  bookSummarySun30: 'रवि, ३० ऑगस्ट २०२६',
  bookSummaryMon31: 'सोम, ३१ ऑगस्ट २०२६',
  bookSummaryTue01: 'मंगळ, १ सप्टेंबर २०२६',
  reviewTitle: 'समीक्षा आणि संमती',
  reviewWhen: 'केव्हा',
  reviewMode: 'पद्धत',
  reviewPatient: 'रुग्ण',
  reviewChange: 'बदला',
  reviewVideoConsult: 'व्हिडिओ सल्ला',
  reviewAudioConsult: 'ऑडिओ सल्ला',
  reviewClinicVisit: 'क्लिनिक भेट',
  reviewReason: 'भेटीचे कारण',
  reviewReasonPlaceholder: 'मुख्य तक्रार थोडक्यात लिहा (ऐच्छिक)',
  reviewAttach: 'अहवाल किंवा फोटो जोडा',
  reviewAttachHint: 'JPG, PNG किंवा PDF, १० MB पर्यंत.',
  reviewAttachFile: 'skin-report.pdf',
  reviewRemoveAttach: 'काढा',
  reviewPayment: 'देयक सारांश',
  reviewDoctorFee: 'डॉक्टरांचे व्यावसायिक शुल्क',
  reviewPlatformFee: 'HelloHomeo प्लॅटफॉर्म शुल्क',
  reviewTaxes: 'कर',
  reviewTotalPayable: 'एकूण देय',
  reviewPriceLocked:
    'ही किंमत या बुकिंगसाठी निश्चित आहे. नंतर कोणतेही अतिरिक्त सुविधा किंवा प्लॅटफॉर्म शुल्क आकारले जात नाही.',
  reviewConsents: 'संमती',
  reviewDataConsent:
    'या ऑनलाइन सल्ल्यासाठी माझ्या वैयक्तिक डेटावर प्रक्रिया करण्यास मी संमती देतो/देते',
  reviewDataConsentBody:
    'तुमचा डेटा केवळ निवडलेल्या आरोग्य व्यावसायिकाकडून वैद्यकीय इतिहास घेण्यासाठी आणि डिजिटल पर्ची देण्यासाठी वापरला जाईल.',
  reviewShareRecords: 'माझे मागील अहवाल या डॉक्टरांसोबत शेअर करा',
  reviewShareRecordsBody:
    'फक्त या रुग्णाच्या मागील पर्च्या, नोंदी आणि अपलोड केलेली कागदपत्रे.',
  reviewReminders: 'या डॉक्टरांना फॉलो-अप रिमाइंडर जोडू द्या.',
  reviewRecordingNote:
    'रेकॉर्डिंग कधीही आपोआप होत नाही. डॉक्टर रेकॉर्ड करू इच्छित असतील तर सल्ल्याच्या सुरुवातीला वेगळी परवानगी विचारली जाईल.',
  reviewPolicy: 'पुन्हा वेळापत्रक आणि रद्द करण्याचे धोरण',
  reviewPolicyFree: '२ तास आधी विनामूल्य वेळापत्रक बदल',
  reviewPolicyFullRefund: '४+ तास आधी १००% रिफंड',
  reviewPolicyHalfRefund: '४ तासांच्या आत ५०%',
  reviewPolicyNoRefund: 'सुरु झाल्यानंतर रिफंड नाही',
  reviewNotEmergency: 'हॅलोहोमियो काय करत नाही',
  reviewNotEmergencyBody:
    'हॅलोहोमियो ही आपत्कालीन सेवा नाही. आपत्कालीन परिस्थितीसाठी जवळच्या हॉस्पिटलशी संपर्क साधा.',
  reviewTotalAmount: 'एकूण रक्कम',
  reviewProceedPay: 'पेमेंट करा',
  payTitle: 'पेमेंट',
  paySlotHeld: 'स्लॉट {time} पर्यंत राखून ठेवला आहे',
  payConsultWith: '{name} यांच्याशी सल्ला · {when}',
  payViewBreakdown: 'तपशील पहा',
  payHideBreakdown: 'तपशील लपवा',
  payMethod: 'पेमेंट पद्धत',
  payUpi: 'UPI',
  payGpay: 'Google Pay',
  payPhonePe: 'PhonePe',
  payPaytm: 'Paytm',
  payEnterUpi: 'UPI ID टाका',
  payUpiPlaceholder: 'name@upi',
  payCards: 'क्रेडिट आणि डेबिट कार्ड',
  paySavedCard: 'HDFC बँक डेबिट कार्ड',
  paySavedCardMeta: '४८२१ ने संपतो',
  paySavedBadge: 'सेव्ह्ड',
  payAddCard: '+ नवीन डेबिट किंवा क्रेडिट कार्ड जोडा',
  payNetbanking: 'नेटबँकिंग',
  paySelectBank: 'बँक निवडा',
  payWallets: 'वॉलेट',
  payBankHdfc: 'HDFC बँक',
  payBankSbi: 'स्टेट बँक ऑफ इंडिया',
  payBankIcici: 'ICICI बँक',
  payWalletAmazon: 'Amazon Pay',
  payWalletMobikwik: 'Mobikwik',
  payPci: 'PCI-DSS अनुरूप',
  payNoStore: 'कार्ड तपशील साठवले जात नाहीत',
  payRefunds: 'मूळ पद्धतीवर रिफंड',
  payCta: '{amount} भरा',
  payStatusSecure: 'सुरक्षित पेमेंट',
  payStatusSuccessTitle: 'अपॉइंटमेंट निश्चित',
  payStatusSuccessMeta: '{amount} भरले · पेमेंट ID {id}',
  payStatusHomeopath: 'होमिओपॅथ',
  payStatusDateTime: 'दिनांक आणि वेळ',
  payStatusConsultType: 'सल्ल्याचा प्रकार',
  payStatusPatient: 'रुग्ण',
  payStatusReminder:
    'आम्ही २४ तास आणि ३० मिनिटे आधी आठवण करून देऊ. जॉईन १० मिनिटे आधी उघडेल.',
  payStatusAddCalendar: 'कॅलेंडरमध्ये जोडा',
  payStatusViewAppointment: 'अपॉइंटमेंट पहा',
  payStatusReceipt: 'पावती डाउनलोड करा',
  payStatusFailedTitle: 'पेमेंट अयशस्वी',
  payStatusFailedBody:
    'तुमचे पैसे वजा झालेले नाहीत. काही रक्कम वजा झाली असेल तर ५–७ कामकाजाच्या दिवसांत परत मिळेल.',
  payStatusReason: 'कारण',
  payStatusFailReason: 'बँकेने व्यवहार नाकारला',
  payStatusAttempt: 'प्रयत्न ID',
  payStatusHoldMore: 'तुमचा {slot} स्लॉट आणखी {time} राखून ठेवला आहे.',
  payStatusRetry: 'पुन्हा पेमेंट करा',
  payStatusOtherMethod: 'दुसरी पद्धत निवडा',
  payStatusOtherSlot: 'दुसरा स्लॉट निवडा',
  payStatusPendingTitle: 'पेमेंट प्रक्रियेत आहे',
  payStatusPendingBody:
    'तुमची बँक हे पेमेंट निश्चित करत आहे. सहसा २ मिनिटांपेक्षा कमी लागते — पुन्हा पैसे भरू नका.',
  payStatusInitiated: 'सुरू',
  payStatusBankConfirming: 'बँक निश्चित करत आहे',
  payStatusConfirmed: 'निश्चित',
  payStatusCheck: 'स्थिती तपासा',
  payStatusSupport: 'सपोर्टशी संपर्क साधा',
  payStatusNotify: 'निश्चित झाल्यावर तुम्हाला SMS आणि अॅप सूचना मिळेल.',
  doctorsBookings: 'तुमच्या बुकिंग',
  doctorsWaitingAcceptance: 'स्वीकृतीची प्रतीक्षा',
  doctorsNoBookings: 'अजून बुकिंग विनंती नाही. सल्ला बुक करा, मग तो इथे दिसेल.',
};
